# Generated by Django 5.1.5 on 2025-08-08 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='fire_reports/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('devam', 'Devam Ediyor'), ('mudahale', 'Müdahale Ediliyor'), ('sonduruldu', 'Söndürüldü')], default='devam', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FireStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('oncesi', 'Yangın Öncesi'), ('ani', 'Yangın Anı'), ('sonrasi', 'Yangın Sonrası')], max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NasaFireData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('brightness', models.FloatField()),
                ('confidence', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_surname', models.CharField(max_length=50, verbose_name='Ad-Soyad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Telefon')),
                ('password', models.CharField(max_length=128, verbose_name='Parola')),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('fake_report_count', models.PositiveIntegerField(default=0)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FakeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('reviewed_by_admin', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yisis_app.firereport')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yisis_app.firereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yisis_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='firereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yisis_app.user'),
        ),
    ]
