# Generated by Django 5.1.5 on 2025-08-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yisis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
