# Generated by Django 5.1.5 on 2025-08-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yisis_app', '0002_user_reset_token_user_reset_token_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
