# Generated by Django 5.1.5 on 2025-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yisis_app', '0003_user_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefon'),
        ),
    ]
