# Generated by Django 5.1.5 on 2025-08-11 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yisis_app', '0004_firestation_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firereport',
            name='photo',
        ),
        migrations.AddField(
            model_name='firereport',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Yangın Fotoğraf URL'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_reports', to='yisis_app.user'),
        ),
    ]
