# Generated by Django 5.1.5 on 2025-08-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yisis_app', '0005_remove_firereport_photo_firereport_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kvkk_onay',
            field=models.BooleanField(default=True),
        ),
    ]
