# Generated by Django 4.2.23 on 2025-08-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yisis_app', '0006_user_kvkk_onay'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('event_type', models.CharField(choices=[('RATE_LIMIT', 'Hız Sınırı Aşımı'), ('DDOS_ATTEMPT', 'DDoS Girişimi'), ('INVALID_AUTH', 'Geçersiz Kimlik'), ('SUSPICIOUS_IP', 'Şüpheli IP')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('CRITICAL', 'Kritik')], max_length=10)),
                ('request_path', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_count', models.IntegerField(default=1)),
                ('details', models.JSONField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='yisis_app_s_ip_addr_4551a4_idx'), models.Index(fields=['event_type'], name='yisis_app_s_event_t_39dc7b_idx'), models.Index(fields=['timestamp'], name='yisis_app_s_timesta_36420f_idx')],
            },
        ),
    ]
