# Generated by Django 5.1.5 on 2025-08-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yisis_app', '0006_user_kvkk_onay'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
