# Generated by Django 5.1.5 on 2025-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yisis_app', '0007_user_expo_push_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakereport',
            options={'verbose_name': 'Asılsız', 'verbose_name_plural': 'Asılsız İhbar'},
        ),
        migrations.AlterModelOptions(
            name='firereport',
            options={'verbose_name': 'Yangın İhbarı', 'verbose_name_plural': 'Yangın İhbarları'},
        ),
        migrations.AlterModelOptions(
            name='firestation',
            options={'verbose_name': 'İstasyonlar', 'verbose_name_plural': 'İstasyonlar'},
        ),
        migrations.AlterModelOptions(
            name='infocontent',
            options={'verbose_name': 'Bilgilendirme', 'verbose_name_plural': 'Bilgilendirme'},
        ),
        migrations.AlterModelOptions(
            name='nasafiredata',
            options={'verbose_name': 'Nasa Verileri', 'verbose_name_plural': 'Nasa Verileri'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Bildirim Geçmişi', 'verbose_name_plural': 'Bildirim Geçmişi'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Kullanıcılar', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AddField(
            model_name='firereport',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Adres'),
        ),
    ]
