# Generated by Django 5.1.5 on 2025-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yisis_app', '0008_alter_fakereport_options_alter_firereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firereport',
            name='decription',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
