# Generated by Django 5.1.5 on 2025-08-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yisis_app', '0009_firereport_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firereport',
            old_name='decription',
            new_name='description',
        ),
    ]
